################### SERVER ##########################
spring.application.name=sistema-de-reservacion-hotel
server.port=8090
# El context-path es global, pero tus Controllers ya tienen /api,
# así que resultará en: http://localhost:8090/api/...
server.servlet.context-path=/api

################### CONEXION BD (H2 - Desarrollo) ##########################
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

################### JPA / HIBERNATE ##########################
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
# 'update' es más seguro en desarrollo para no perder data al reiniciar;
# usa 'créate' solo si necesitas limpiar la BD en cada ejecución.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 CONSOLE (Acceso: http://localhost:8090/api/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

################### DATA INITIALIZATION ##########################
# Permite cargar datos iniciales en el arranque
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

################### SWAGGER / OPENAPI ##########################
# Acceso UI: http://localhost:8090/api/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html